/**
 * Security Levels — automatic classification of CodeRule configurations.
 *
 * Philosophy:
 *   OmniCodex permite distintos niveles de seguridad en la generación de códigos.
 *   Sin embargo, solo las reglas que incorporan autenticidad criptográfica (HMAC)
 *   ofrecen protección frente a la generación fraudulenta de códigos. El sistema
 *   clasifica automáticamente cada regla según su nivel de seguridad y muestra
 *   advertencias explícitas cuando la configuración es vulnerable.
 *
 * Levels:
 *   0 — OPEN         No HMAC, no check digit. Easily forgeable.
 *   1 — CONTROLLED   Check digit and/or random serial, but no cryptographic auth.
 *   2 — AUTHENTICATED HMAC authenticator present — cryptographic proof of origin.
 *   3 — PROTECTED    HMAC + enhanced anti-fraud controls (geo-fencing, strict rate limits, etc.)
 */

export type SecurityLevelCode = 'OPEN' | 'CONTROLLED' | 'AUTHENTICATED' | 'PROTECTED';

export interface SecurityLevel {
  /** Numeric level 0-3 */
  level: number;
  /** Named code */
  code: SecurityLevelCode;
  /** Human-readable label */
  label: string;
  /** Whether this configuration is considered safe for production campaigns */
  is_production_safe: boolean;
  /** Explanation of why this level was assigned */
  reason: string;
  /** Actionable warnings for the operator */
  warnings: string[];
}

export interface SecurityLevelInput {
  hasCheckDigit: boolean;
  structureDef: {
    segments?: Array<{
      type: string;
      length: number;
      values?: string[];
      value?: string;
    }>;
  };
  fabricantSecret?: string | null;
  allowedCountries?: string[];
  maxRedemptions?: number;
  /** Estimated entropy bits (from linter) */
  estimatedEntropy?: number;
}

/**
 * Compute the security level for a CodeRule configuration.
 *
 * The logic is deterministic and based purely on the rule's structural properties:
 *
 *   Level 3 (PROTECTED):  HMAC present + TAG >= 8 + at least one anti-fraud control
 *   Level 2 (AUTHENTICATED): HMAC present + fabricant secret configured
 *   Level 1 (CONTROLLED):  Check digit OR random serial with decent entropy, but no HMAC
 *   Level 0 (OPEN):        Everything else
 */
export function computeSecurityLevel(input: SecurityLevelInput): SecurityLevel {
  const segments = input.structureDef?.segments || [];
  const hmacSegment = segments.find((s) => s.type === 'hmac');
  const hasHmac = !!hmacSegment;
  const hasSecret = !!input.fabricantSecret;
  const hasCheckDigit = input.hasCheckDigit;
  const hasGeoFencing = input.allowedCountries && input.allowedCountries.length > 0;
  const hasStrictRedemptions = input.maxRedemptions === 1;
  const hmacLength = hmacSegment?.length || 0;

  // Count random segments (numeric ranges, alpha, alphanumeric — not fixed/date/enum/check/hmac)
  const randomSegments = segments.filter(
    (s) => s.type === 'numeric' || s.type === 'alpha' || s.type === 'alphanumeric',
  );
  const hasRandomSerial = randomSegments.length > 0;

  const entropy = input.estimatedEntropy ?? estimateEntropyFromSegments(segments);
  const warnings: string[] = [];

  // ── Level 3: PROTECTED ──────────────────────────────────────────────
  if (hasHmac && hasSecret && hmacLength >= 8) {
    const antiFraudControls: string[] = [];
    if (hasGeoFencing) antiFraudControls.push('geo-fencing');
    if (hasStrictRedemptions) antiFraudControls.push('single-use');
    if (entropy >= 40) antiFraudControls.push('high-entropy');

    if (antiFraudControls.length >= 1) {
      if (hmacLength < 10) {
        warnings.push(
          `HMAC TAG is ${hmacLength} chars. Consider 10+ for maximum security.`,
        );
      }
      return {
        level: 3,
        code: 'PROTECTED',
        label: 'Alto — Protegido',
        is_production_safe: true,
        reason: `HMAC authenticator (${hmacLength} chars, BASE32) + anti-fraud: ${antiFraudControls.join(', ')}`,
        warnings,
      };
    }
  }

  // ── Level 2: AUTHENTICATED ──────────────────────────────────────────
  if (hasHmac && hasSecret) {
    if (hmacLength < 8) {
      warnings.push(
        `HMAC TAG is only ${hmacLength} chars. Recommended: at least 8 for adequate security.`,
      );
    }
    if (!hasGeoFencing) {
      warnings.push('Consider enabling geo-fencing for production campaigns.');
    }
    return {
      level: 2,
      code: 'AUTHENTICATED',
      label: 'Seguro — Autenticado',
      is_production_safe: true,
      reason: `HMAC authenticator present (${hmacLength} chars). Codes are cryptographically verified.`,
      warnings,
    };
  }

  // ── Level 1: CONTROLLED ─────────────────────────────────────────────
  if (hasCheckDigit || (hasRandomSerial && entropy >= 20)) {
    warnings.push(
      'No HMAC authenticator. Codes can be generated by anyone who understands the structure.',
    );
    if (!hasCheckDigit) {
      warnings.push('No check digit configured. Typos will not be detected.');
    }
    if (entropy < 30) {
      warnings.push(
        `Estimated entropy is ~${entropy} bits. Consider adding more random segments.`,
      );
    }

    // Special case: HMAC defined but no secret
    if (hasHmac && !hasSecret) {
      warnings.push(
        'HMAC segment defined but no fabricant_secret provided. HMAC verification is disabled.',
      );
    }

    return {
      level: 1,
      code: 'CONTROLLED',
      label: 'Básico — Controlado',
      is_production_safe: false,
      reason: hasCheckDigit
        ? 'Check digit provides error detection, but no cryptographic authentication.'
        : 'Random serial provides some uniqueness, but codes are forgeable.',
      warnings,
    };
  }

  // ── Level 0: OPEN ───────────────────────────────────────────────────
  warnings.push(
    'This rule has no cryptographic authentication (HMAC) and no check digit.',
  );
  warnings.push(
    'Codes can be trivially generated by third parties.',
  );
  warnings.push(
    'Only use for awareness campaigns or non-critical promotions.',
  );

  if (entropy < 20) {
    warnings.push(
      `Extremely low entropy (~${entropy} bits). Codes are trivially guessable.`,
    );
  }

  return {
    level: 0,
    code: 'OPEN',
    label: 'No seguro — Abierto',
    is_production_safe: false,
    reason: 'No integrity verification. Any code matching the structure will be accepted.',
    warnings,
  };
}

/**
 * Estimate entropy bits from segment definitions.
 * Used as fallback when estimatedEntropy is not provided.
 */
function estimateEntropyFromSegments(
  segments: Array<{ type: string; length: number; values?: string[] }>,
): number {
  let totalBits = 0;

  for (const seg of segments) {
    switch (seg.type) {
      case 'fixed':
      case 'check':
      case 'hmac':
        break; // Deterministic — 0 entropy
      case 'numeric':
        totalBits += seg.length * Math.log2(10);
        break;
      case 'alpha':
        totalBits += seg.length * Math.log2(26);
        break;
      case 'alphanumeric':
        totalBits += seg.length * Math.log2(36);
        break;
      case 'enum':
        if (seg.values && seg.values.length > 1) {
          totalBits += Math.log2(seg.values.length);
        }
        break;
      case 'date':
        totalBits += 12; // ~365 * 10 years
        break;
    }
  }

  return Math.floor(totalBits);
}
